### PR TITLE
Added paragraph indent option

### PR DESCRIPTION
**Pull request by KenH2000**
The update adds a paragraph indent option (enabled with -p or --para-indent). When enabled, the text will be formatted so that paragraphs are separated by indent instead of the blank line space in-between. The update requires minor changes to the files main.c, text.c, and text.h.

### CODE REVIEW

**Comment by kevinboone** [comment]
Hi. Thank you for this work. I tested your PR, and it does what I think it is supposed to do; that is, it writes a <style> section into the generated HTML embedded into the EPUB. I can see a couple of slight problems, neither of which are showstoppers, I guess.

1. The calibre ebook-viewer utility doesn't respect this way of setting styles -- at least, it did not for me. I don't know if perhaps it can be configured to. Other viewers might -- do you have one in particular I should test?

2. The default method of separating paras (blank line) does not cause (in my viewers) an oddity when the indent is applied to the first para in a document. The viewer seems to absorb the 'extra' paragraph space. However, when using an indent, it looks a little odd if the indent is applied to the first line of the document. Can a style be defined that only applies the indent after the first paragraph? And would it be accepted by epub viewers? Have I even articulated this problem in a way that makes sense?

I think I've seen EPUB documents that are formatted to use indents for paragraphs, and that manage not to indent the first paragraph -- but I have no idea how this is achieved. Maybe they use CSS?

Your comments are welcome.

**Comment by KenH2000** [comment]
Thank you for considering my PR.  I like the 'no line space' option because it gives a little more vertical space on a 6" ereader screen.  And it is an option that can be used or not and should not otherwise adversely affect the program.

Unfortunately, I found a bigger problem with the main branch (unchanged) txt2epub that we may need to address if possible.  I don't what is causing it.  When I create an epub with chapters, the book displays in Calibre's reader normally, but in ereaders (tested in Kobo, Nook, & Readman) any chapter > 1 only shows a blank page.  Turning to the next page causes the ereader to jump several pages (to the next chapter apparently), and then again only displays a blank page. 

However, when I create an epub with no chapters (from a single text file), then it works normally on all ereaders -- but then, of course, there is no TOC.  

I wish we could fix it because the program (other than this issue) does exactly what I want it to do.

Addressing your other comments:

1.  The txt to epub I created did have strange behavior in Calibre's reader using the new -p setting.  The first several paragraphs displayed with the blank linefeed intact.  After paging down a few times, the blank line feeds disappeared, and the book displayed as it should with no blank line-feeds.  Other than the blanks line-feeds at the beginning, everything else displayed as intended.  BUT, the epub displayed entirely with no blank line-feeds (as intended) in my Kobo ereader.

2.  This was an interesting comment.  I had never noticed that the 1st paragraph was not indented in epubs, so  I looked through several of my epubs from other sources.  Several were as you described but some had an indent (ex. Pride and Prejudice).  Since it seems to be acceptable either way, I'm willing to leave it as is for now.  I am more concerned about the 'blank chapters' issue.

**Comment by kevinboone** [comment]
I wasn't able to reproduce the 'blank chapters' problem on my Kobo Forma. Perhaps you would be kind enough to log a bug and, ideally, provide sample input or output that shows the problem? I would like to address this, if I can.

I'm happy to include your PR, anyway -- I'm not going quibble about valuable contributions :)

**Comment by KenH2000** [comment]
Turns out, cancelling the indent on the first paragraph is very easy.  In style tag add this:
<pre>
<style>
...other style stuff

p.first-in-chapter {
  text-indent: 0;
}

...other style stuff
</style>
</pre>
then in the body of the html, do this:

     <p class="first-in-chapter" \>
    my first para in chapter with no indent...
    </p>
    <p>remaining paragraphs...</p>
...etc

I'll post a short book sample that exhibits the chapter problem on my Kobo
(It is a Kobo touch glow).

I suspect the problem is in the toc.ncx file.  
I looked at another epub, and the file had simpler looking code for the navmap section.
Also, they used xhtml instead of html.  I don't know if that matters.

    <navMap>
    <navPoint id="c001" playOrder="1">
      <navLabel>
        <text>Title Page</text>
      </navLabel>
      <content src="c001.xhtml"/>
    </navPoint>
    <navPoint id="c002" playOrder="2">
      <navLabel>
        <text>Copyright Page</text>
      </navLabel>
      <content src="c002.xhtml"/>
     </navPoint>
...etc

I tried making these changes to my txt2epub book, by unzipping, editing the files in the format above, then re-zipping, but the Kobo refused to open the book after that.

**Comment by kevinboone** [comment]
Do you want to submit a new PR for the indent enhancement (with first-para improvement)? That way you'll get credit as a contributor -- what little credit there is to be had. I'm happy to merge your contribution, with or without the latest changes you suggest. Please log a bug for the other thing, or I'll get the issues mixed up -- I'm not getting any younger ;)

**Comment by KenH2000** [comment]
OK, I submitted a bug report and put a new text.c file in 'tests' that does the 1st paragraph no-indent.

**Comment by kevinboone** [comment]
Thank you.

**Pull request merged**
